"""Render results generated by benchmark; no research performance is fabricated."""

import argparse
from pathlib import Path
import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import pandas as pd


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--input", default="outputs/benchmark.csv")
    p.add_argument("--output", default="outputs/benchmark.svg")
    a = p.parse_args()
    df = pd.read_csv(a.input).dropna(subset=["blocking_pairs"])
    if "completed" in df:
        df = df[df.completed.astype(str).str.lower().eq("true")]
    df = df[df.blocking_pairs.apply(lambda x: x != float("inf"))]
    if df.empty:
        raise ValueError("No completed method to plot")
    plt.rcParams.update({"font.family": "DejaVu Sans", "svg.fonttype": "none"})
    fig, ax = plt.subplots(figsize=(9, 4.5))
    bars = ax.bar(df.method, df.blocking_pairs, color="#2563eb")
    ax.bar_label(bars, padding=3)
    ax.set_ylabel("Final blocking pairs (lower is better)")
    ax.set_title(
        "Synthetic demonstration • not thesis results", loc="left", fontweight="bold"
    )
    ax.spines[["top", "right"]].set_visible(False)
    ax.set_ylim(0, max(1, df.blocking_pairs.max() * 1.2))
    dest = Path(a.output)
    dest.parent.mkdir(parents=True, exist_ok=True)
    fig.tight_layout()
    fig.savefig(dest)
    plt.close(fig)


if __name__ == "__main__":
    main()
